libstdc++: Fix build failure in tzdb.cc
The changes in r17-2047-gb12fdd95251178 cause a bootstrap failure if
ATOMIC_POINTER_LOCK_FREE != 2 && ATOMIC_INT_LOCK_FREE == 2 is true for
the target:

.../tzdb.cc: In static member function ‘static const std::chrono::tzdb& std::chrono::tzdb_list::_Node::_S_replace_head(std::shared_ptr<std::chrono::tzdb_list::_Node>, std::shared_ptr<std::chrono::tzdb_list::_Node>)’:
.../tzdb.cc:1617:22: error: ‘struct std::chrono::tzdb_list::_Node::NumLeapSeconds’ has no member named ‘set_locked’
 1617 |     num_leap_seconds.set_locked(new_head_ptr->db.leap_seconds.size(), lock);
      |                      ^~~~~~~~~~

This fix defines the 'set_atomically' and 'set_locked' functions
unconditionally, and renames the former to just 'set'. This fixes the
mismatch between the atomic pointer and atomic int conditions, as both
functions are available for both branches of the #if/#else in
_Node::_S_replace_head.

libstdc++-v3/ChangeLog:

	* src/c++20/tzdb.cc (_Node::NumLeapSeconds::set_atomically):
	Rename to set and define unconditionally.
	(_Node::NumLeapSeconds::set_locked): Define unconditionally.